<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Z</name>
   <tag></tag>
   <elementGuidId>1dbe4c0b-942d-4cc3-9cae-edfb39dc409a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.flex.h-full.w-full.items-center.justify-center.rounded-full.bg-muted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Toggle theme'])[1]/following::span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d902478a-4f5e-41b6-bc41-8ec16584bfb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>flex h-full w-full items-center justify-center rounded-full bg-muted</value>
      <webElementGuid>67386365-108d-41d8-b1ff-3607e6586b25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Z</value>
      <webElementGuid>e321c6f6-ba94-46c8-b82e-b7e54409ef13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;dark&quot;]/body[@class=&quot;__className_d65c78&quot;]/div[@class=&quot;min-h-screen bg-white/90 dark:bg-black/50 pl-0 transition-all duration-300 ease-in-out data-[sidebar=closed]:pl-0 sm:pl-[--sidebar-width]&quot;]/main[@class=&quot;flex flex-1 flex-col transition-all duration-300 ease-in-out&quot;]/div[@class=&quot;z-[30] sticky top-0 w-full bg-background border-b backdrop-blur-sm dark:bg-background border-border/40 pl-1 pr-2 md:px-5&quot;]/nav[@class=&quot;flex h-12 items-center justify-between&quot;]/div[@class=&quot;flex items-center gap-2&quot;]/button[2]/span[@class=&quot;relative flex shrink-0 overflow-hidden rounded-full cursor-pointer h-8 w-8&quot;]/span[@class=&quot;flex h-full w-full items-center justify-center rounded-full bg-muted&quot;]</value>
      <webElementGuid>accb660e-9b8c-4957-878a-863c3cf57359</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toggle theme'])[1]/following::span[2]</value>
      <webElementGuid>64d07450-573a-4a1c-a4e8-983e6bb47862</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='| enterprise'])[1]/following::span[3]</value>
      <webElementGuid>d58b1bf0-ce6e-4b52-8062-0f2ece0a63f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Administration'])[1]/preceding::span[1]</value>
      <webElementGuid>898c4c65-7491-4b3e-a471-4644a8cc8e20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Employee'])[2]/preceding::span[1]</value>
      <webElementGuid>e435cd44-caea-42e0-88fd-3ead38120cca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Z']/parent::*</value>
      <webElementGuid>42b81634-080c-4880-af66-ec9ac6e087ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/span/span</value>
      <webElementGuid>2af80587-4d6f-445a-8d0a-6b8ed72187d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Z' or . = 'Z')]</value>
      <webElementGuid>519d45fb-7901-4b98-9061-3d37024a5dd0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
